#
# Dockerfile for building go applications
#

# Small, thin, simple
FROM golang:1.8-alpine

# Install build dependency packages
RUN apk update && apk add make git

# Working Dir
WORKDIR /go/src/statseventrelay

# Volume
VOLUME ["/go/src/statseventrelay"]

# Default entry point
ENTRYPOINT ["make"]
